# Generated by Django 6.0.3 on 2026-03-11 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('entrepreneur_name', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('segment', models.IntegerField(choices=[(0, 'Tecnologia'), (1, 'Comércio'), (2, 'Indústria'), (3, 'Serviços'), (4, 'Agronegócio')])),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enterprises',
                'ordering': ['created_at'],
            },
        ),
    ]
